### ISSUE TITLE
Connection is failing while using certificate connection

### ISSUE THREAD

**Issue by bhattisatish** [MeltanoLabs/tap-snowflake#59]
I am using a service account with certificate authentication. 
When I build a ELT pipeline, the extraction process fails with a connection error
`The certificate is revoked or could not be validated: hostname=sfc-ie-ds1-27-customer-stage.s3.eu-west-1.amazonaws.com`

I tried running a simple `connect` and even that fails.
Running any command on the tap fails with the same error. For e.g. `meltano invoke tap-snowflake  --discover` fails similarly.

**Comment by bhattisatish** [comment]
Looks like an issue with recent snowflake certificate changes. See [here](https://status.snowflake.com/incidents/txclg2cyzq32).

Things started to work, with the pining the certifi==2025.1.31. An example change in meltano.yml
```
  extractors:
  - name: tap-snowflake
    variant: meltanolabs
    pip_url: meltanolabs-tap-snowflake certifi==2025.1.31 
```
